databases:
  - name: waris
    databaseName: waris
    user: waris_user

services:
  - type: web
    name: warisapp
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: waris
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false